CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
IMAGE_SEGMENT_TOKEN_INDEX = -300
DEFAULT_IMAGE_TOKEN = "<video>"
DEFAULT_IMAGE_SEGMENT_TOKEN = "<video segment>"

